#!/bin/bash
# Round 32: close the loose end from round 31. The control arm (im-v15 data, new
# block forced to zero) was only ever used as the *control* in an arm-vs-arm
# comparison; its own strength was never measured. It is the cleanest probe of a
# question that matters for the recipe: does from-scratch training on data
# generated by the *current* best beat the model that was trained on data
# generated by an older, weaker policy? ck-ab came from im-v12 (generated by the
# round-26 model); im-v15 was generated by ck-ab itself.
cd ~/Documents/mmoyager/mmoyager_mahjong
E=/tmp/mmj-perf2/release/mmj-eval
echo "=== same batch: incumbent, then the three control replicas (4800 games, seed 4242) ==="
printf "  %-12s " "ck-ab(737)"
$E --a data/checkpoints/ck-ab.bin --b efficiency-v2 --games 4800 --seed 4242 --json | python3 -c "
import json,sys;d=json.load(sys.stdin);print(f\"vs v2 {d['avg_a']-d['avg_b']:+8.1f}\")"
for seed in 1 2 3; do
  printf "  %-12s " "ctl-$seed(753/0)"
  $E --a /tmp/ctl-$seed.bin --b efficiency-v2 --games 4800 --seed 4242 --json | python3 -c "
import json,sys;d=json.load(sys.stdin);print(f\"vs v2 {d['avg_a']-d['avg_b']:+8.1f}\")"
done
echo "=== direct: control replicas against the incumbent (4800 games, seed 4242) ==="
for seed in 1 2 3; do
  printf "  %-12s " "ctl-$seed vs ck-ab"
  $E --a /tmp/ctl-$seed.bin --b data/checkpoints/ck-ab.bin --games 4800 --seed 4242 --json | python3 -c "
import json,sys;d=json.load(sys.stdin);print(f\"margin {d['avg_a']-d['avg_b']:+8.1f}  firsts {d['first_rate_a']:.4f}\")"
done
echo "CONTROL ARM DONE"
