#!/bin/bash
set -e
# Round 32: does from-scratch training on data generated by the *current* best
# beat ck-ab, which was trained on data generated by an older, weaker policy?
#
# The control arm of round 31 was supposed to answer this but was flawed: it
# zeroed the new block only in the training batches, so those first-layer weights
# kept their random initialisation while inference fed them the real values. The
# honest control is a 737-dimension copy of the same data (`im-v15-737.bin`),
# trained by the old build, so training and inference agree exactly.
cd ~/Documents/mmoyager/mmoyager_mahjong
OLD=./target/release/mmj-selfplay
OLDE=./target/release/mmj-eval
for p in $(pgrep -f "loop.py") $(pgrep -f "train.py") $(pgrep -f "mmj-selfplay generate"); do
  kill -9 $p 2>/dev/null
done
sleep 3
echo "=== 1. the converted data must be readable and match the 737 prefix ==="
.venv/bin/python -c "
import sys; sys.path.insert(0, 'python/trainer')
import mmjdata, numpy as np
a = mmjdata.load('data/selfplay/im-v15.bin', 5000)
b = mmjdata.load('data/selfplay/im-v15-737.bin', 5000)
print(f'  source {a.count} x {a.feature_dim}, control {b.count} x {b.feature_dim}')
assert a.count == b.count
assert np.array_equal(a.features[:, :737], b.features[:, :737]), 'feature prefix differs'
assert np.array_equal(a.masks, b.masks) and np.array_equal(a.actions, b.actions)
assert np.allclose(a.returns, b.returns)
print('  prefix, masks, actions and returns all match')"
echo "=== 2. three from-scratch replicas on the fresh data, old (737) features ==="
for seed in 1 2 3; do
  echo "  --- refresh $seed ---"
  .venv/bin/python -u python/trainer/train.py --data data/selfplay/im-v15-737.bin \
    --hidden 768,768 --epochs 4 --lr 3e-4 --lr-decay 0.8 --max-records 900000 \
    --value-coef 0.5 --return-scale 0.25 --seed $seed --threads 8 \
    --out /tmp/ref-$seed.bin --note datarefresh-$seed 2>&1 | grep -E "feature_dim|epoch 4|saved"
done
echo "=== 3. one batch (9600 games, seed 4242) ==="
printf "  %-12s " "ck-ab"
$OLDE --a data/checkpoints/ck-ab.bin --b efficiency-v2 --games 9600 --seed 4242 --json | python3 -c "
import json,sys;d=json.load(sys.stdin);print(f\"vs v2 {d['avg_a']-d['avg_b']:+8.1f}  rank {d['avg_rank_a']:.4f}\")"
for seed in 1 2 3; do
  printf "  %-12s " "ref-$seed"
  $OLDE --a /tmp/ref-$seed.bin --b efficiency-v2 --games 9600 --seed 4242 --json | python3 -c "
import json,sys;d=json.load(sys.stdin);print(f\"vs v2 {d['avg_a']-d['avg_b']:+8.1f}  rank {d['avg_rank_a']:.4f}\")"
done
echo "=== 4. direct: each refresh model against the incumbent ==="
for seed in 1 2 3; do
  printf "  %-12s " "ref-$seed vs ck-ab"
  $OLDE --a /tmp/ref-$seed.bin --b data/checkpoints/ck-ab.bin --games 9600 --seed 4242 --json | python3 -c "
import json,sys;d=json.load(sys.stdin);print(f\"margin {d['avg_a']-d['avg_b']:+8.1f}  firsts {d['first_rate_a']:.4f}\")"
done
echo "=== 5. restarting the loop ==="
nohup .venv/bin/python -u python/trainer/loop.py --resume --forever --dagger-loop --search-modes \
  --primary-spec efficiency-v2 --yardstick2 efficiency --eval-games 9600 --accept-margin 60 \
  --confirm-runs 2 --early-stop-slack 100 --bootstrap-lr 3e-4 --bootstrap-records 900000 \
  --bootstrap-epochs 4 --bootstrap-data data/selfplay/im-v12.bin --value-coef 0.25 \
  --entropy-coef 0.005 --max-records 900000 --threads 4 --accept-on direct --abs-every 5 \
  > data/logs/loop-v25.out 2>&1 &
echo "loop pid=$!"
echo "DATAREFRESH DONE"
