#!/bin/bash
# Round 31, control arm for the threat-read block. im-v15 was generated by the
# incumbent, which is a *stronger* player than the one that generated the data
# ck-ab was trained on, so a straight win by the feature arm would be confounded.
# This arm uses the identical data, architecture and recipe with the new block
# forced to zero, so the only difference between the arms is whether the block is
# available. Both arms are then measured in one batch.
cd ~/Documents/mmoyager/mmoyager_mahjong
NEWE=/tmp/mmj-perf2/release/mmj-eval
while pgrep -f "threatread.sh" > /dev/null; do sleep 20; done
echo "=== control replicas (block zeroed) ==="
for seed in 1 2 3; do
  echo "  --- control $seed ---"
  .venv/bin/python -u python/trainer/train.py --data data/selfplay/im-v15.bin \
    --hidden 768,768 --epochs 4 --lr 3e-4 --lr-decay 0.8 --max-records 900000 \
    --value-coef 0.5 --return-scale 0.25 --seed $seed --threads 8 \
    --zero-features 737:753 --out /tmp/ctl-$seed.bin --note threatread-control-$seed 2>&1 \
    | grep -E "control arm|epoch 4|saved"
done
echo "=== one batch: ck-ab, feature arm, control arm (4800 games, seed 4242) ==="
printf "  %-14s " "ck-ab(737)"
$NEWE --a data/checkpoints/ck-ab.bin --b efficiency-v2 --games 4800 --seed 4242 --json | python3 -c "
import json,sys;d=json.load(sys.stdin);print(f\"{d['avg_a']-d['avg_b']:+8.1f}\")"
for seed in 1 2 3; do
  printf "  %-14s " "feature-$seed"
  $NEWE --a /tmp/tr-$seed.bin --b efficiency-v2 --games 4800 --seed 4242 --json | python3 -c "
import json,sys;d=json.load(sys.stdin);print(f\"{d['avg_a']-d['avg_b']:+8.1f}\")"
done
for seed in 1 2 3; do
  printf "  %-14s " "control-$seed"
  $NEWE --a /tmp/ctl-$seed.bin --b efficiency-v2 --games 4800 --seed 4242 --json | python3 -c "
import json,sys;d=json.load(sys.stdin);print(f\"{d['avg_a']-d['avg_b']:+8.1f}\")"
done
echo "THREATREAD CONTROL DONE"
